### ISSUE TITLE
 Blackhat official website can not download your keynote

### ISSUE THREAD

**Issue by wanming2008** [REhints/BlackHat_2017#1]
https://www.blackhat.com/docs/us-17/thursday/us-17-Branco-Firmware-Is-The-New-Black-Analyzing-Past-Three-Years-Of-BIOS-UEFI-Security-Vulnerabilities

ERROR... PAGE NOT FOUND

**Comment by matrosov** [comment]
Try this one: https://github.com/rrbranco/BlackHat2017/blob/master/BlackHat2017-BlackBIOS-v0.13-Published.pdf

**Comment by wanming2008** [comment]
i already download it  i just mean balckhat maybe made a mistake  thanks  for answer. Looking forward to seeing you in Las Vegas next year
